version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 30
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
