require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*'

Rails:
  Enabled: true

RSpec/DescribedClass:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
    - 'config.ru'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 128
