AllCops:
  Exclude:
    - '**/Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
    - 'config.ru'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 128
