version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.0-alpine
        environment:
          RDB_URL_BASE: postgres://postgres:@localhost
      - image: postgres:9.5-alpine
    working_directory: /home/circleci/github-organization-watcher
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apk add --update --no-cache build-base postgresql-dev postgresql-libs nodejs tzdata
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Rails Best Practices
          command: bundle exec rails_best_practices .
      - run:
          name: Run RuboCop
          command: bundle exec rubocop
      - run:
          name: Run Tests
          command: bundle exec rake spec
