version: '3'

services:
  app:
    image: masutaka/github-organization-watcher
    build: .
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    ports:
      - 13000:3000
    environment:
      BUNDLE_APP_CONFIG: /app/vendor/bundle
      RDB_URL_BASE: postgres://postgres:@rdb
      REDIS_URL: redis://redis:6379
      GITHUB_KEY: $GITHUB_KEY
      GITHUB_SECRET: $GITHUB_SECRET
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - rdb
      - redis
  rdb:
    image: postgres:9.5-alpine
    ports:
      - 15432:5432 # for convenience
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379 # for convenience
    volumes:
      - redis_data:/data

volumes:
  bundle:
  postgres_data:
  redis_data:
