version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.3-alpine
        environment:
          RDB_URL_BASE: postgres://postgres:@localhost
          REDIS_URL: redis://localhost:6379
      - image: postgres:9.5-alpine
      - image: redis:3.2-alpine
    working_directory: /work
    steps:
      - run:
          name: Install System Dependencies
          command: |
            # See also https://circleci.com/docs/2.0/custom-images/#adding-required-and-custom-tools-or-files
            apk add --update --no-cache git openssh-client tar gzip ca-certificates \
              build-base postgresql-dev postgresql-libs nodejs tzdata
            gem install -N bundler
      - checkout
      - restore_cache:
          name: Restore bundler cache
          keys:
            - gems-{{ arch }}-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ arch }}-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Install Ruby Dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3
            bundle clean
      - save_cache:
          name: Save bundler cache
          key: gems-{{ arch }}-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle
      - run:
          name: Create DB
          command: rake db:create db:schema:load --trace
      - run:
          name: Run Rails Best Practices
          command: rails_best_practices .
      - run:
          name: Run RuboCop
          command: rubocop
      - run:
          name: Run Tests
          command: rspec --format progress --format RspecJunitFormatter -o test-reports/junit.xml
      - store_test_results:
          path: test-reports/
