version: 2.1

orbs:
  pushover: masutaka/pushover@2

executors:
  app:
    docker:
      - image: cimg/ruby:2.7.2-node
        environment:
          RDB_URL_BASE: postgres://postgres:@localhost
          REDIS_URL: redis://localhost:6379
      - image: postgres:9.5-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: redis:4.0-alpine
    working_directory: ~/repo

commands:
  bundle_install:
    steps:
      - restore_cache:
          name: Restore bundler cache
          keys:
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Install Ruby Dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3 --path=vendor/bundle
            bundle clean
      - save_cache:
          name: Save bundler cache
          key: gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
  rubocop:
    steps:
      - run:
          name: Run RuboCop
          command: bundle exec rubocop
  rails_best_practices:
    steps:
      - run:
          name: Run Rails Best Practices
          command: bundle exec rails_best_practices .
  rspec:
    steps:
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-reports/junit.xml
      - store_test_results:
          path: test-reports/

jobs:
  build:
    executor: app
    steps:
      - checkout
      - bundle_install
      - rubocop
      - rails_best_practices
      - rspec
      - pushover/notify-on-failure

workflows:
  version: 2
  ordinary:
    jobs:
      - build
