version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
