version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "monthly"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          update_type: "semver:patch"
